// Motivational Quotes Database - 1000 Quotes
const motivationalQuotes = [
    // Career & Professional Success
    "Your career is a marathon, not a sprint. Keep your thesis progress steady and consistent.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Every expert was once a beginner. Every pro was once an amateur. Every icon was once an unknown.",
    "The future belongs to those who believe in the beauty of their dreams and work toward them daily.",
    "Your thesis is not just a document, it's a testament to your intellectual journey.",
    "Success is not how high you have climbed, but how you make a positive difference to the world through your research.",
    "Believe in your research, believe in your findings, believe in yourself.",
    "The only way to do great academic work is to love what you're studying.",
    "Your limitations exist only in your mind. Your thesis will prove your capabilities.",
    "Push through the difficult chapters, because no one else can write your story.",
    
    // Thesis Writing & Academic Perseverance
    "Great research never comes from staying in your academic comfort zone.",
    "Dream your thesis. Plan your thesis. Write your thesis.",
    "Academic success doesn't just find you. You have to research, write, and earn it.",
    "The harder you work on your thesis, the prouder you'll feel at graduation.",
    "Don't stop when you're tired of writing. Stop when your thesis is complete.",
    "Wake up with determination to write. Go to bed with satisfaction from progress made.",
    "Write something today that your future graduate self will thank you for.",
    "Little writing sessions make big thesis progress.",
    "Thesis writing is hard, but hard does not mean impossible.",
    "Don't wait for perfect research conditions. Create productive writing habits.",
    
    // Career Development & Professional Growth
    "If you want to achieve academic excellence, stop asking if you're good enough.",
    "The key to thesis success is to focus on progress, not perfection.",
    "Research bigger. Think bigger. Contribute bigger.",
    "Don't be afraid to challenge existing theories to make groundbreaking discoveries.",
    "The difference between a good thesis and an extraordinary one is thorough research.",
    "Academic champions keep writing until they get their argument right.",
    "You are not a product of your academic circumstances. You are a product of your research decisions.",
    "You are never too experienced to learn something new for your thesis.",
    "The only researcher you are destined to become is the one you decide to be.",
    "What lies behind your research and what lies ahead are small compared to the knowledge within you.",
    
    // Courage & Confidence
    "Be yourself; everyone else is already taken.",
    "You miss 100% of the shots you don't take.",
    "Whether you think you can or you think you can't, you're right.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "A person who never made a mistake never tried anything new.",
    "The way to get started is to quit talking and begin doing.",
    "Innovation distinguishes between a leader and a follower.",
    "Life is what happens to you while you're busy making other plans.",
    "The future belongs to those who prepare for it today.",
    "You can't use up creativity. The more you use, the more you have.",
    
    // Motivation & Inspiration
    "Strive not to be a success, but rather to be of value.",
    "Two roads diverged in a wood, and I took the one less traveled by, and that made all the difference.",
    "I attribute my success to this: I never gave or took any excuse.",
    "You become what you believe.",
    "I would rather die of passion than of boredom.",
    "A truly rich man is one whose children run into his arms when his hands are empty.",
    "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
    "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
    "Build your own dreams, or someone else will hire you to build theirs.",
    "The battles that count aren't the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that's where it's at.",
    
    // Education & Academic Excellence
    "Education is the passport to the future, and your thesis is your boarding pass.",
    "You are not just a student, but a researcher contributing to human knowledge.",
    "It is the mark of an educated mind to be able to question, analyze, and synthesize.",
    "Study as if your career depends on it, because it does.",
    "The only true academic wisdom is knowing that research never truly ends.",
    "In researching you will discover, and in writing you will clarify your thoughts.",
    "Your thesis is the result of all your learning transforming into original contribution.",
    "Develop a passion for your research topic. It will carry you through long writing sessions.",
    "The beautiful thing about your education is that it becomes part of who you are.",
    "An investment in your thesis is an investment in your future career.",
    
    // Personal Growth
    "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.",
    "Try not to become a person of success, but rather try to become a person of value.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind.",
    "You have power over your mind – not outside events. Realize this, and you will find strength.",
    "The happiness of your life depends upon the quality of your thoughts.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "You have been critical of yourself for years, and it hasn't worked. Try approving of yourself and see what happens.",
    "The most beautiful people I've known are those who have known trials, have known struggles, have known loss, and have found their way out of those depths.",
    "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.",
    
    // Academic Time Management & Productivity
    "Thesis time is what you want most, so use it wisely for maximum progress.",
    "The trouble with procrastination is you think you have unlimited time to write.",
    "Yesterday's research is foundation, tomorrow's writing is possibility, today's work is progress.",
    "Don't put off until tomorrow the thesis chapter you can write today.",
    "Deadlines fly over us, but productive work leaves lasting achievements behind.",
    "Better to submit three hours early than one minute after the deadline.",
    "Research time is the most valuable investment in your academic career.",
    "The key is not to prioritize distractions, but to schedule focused writing sessions.",
    "You may delay your thesis work, but graduation requirements will not wait.",
    "Writing time is more valuable than perfect conditions. You can improve conditions, but you cannot recover lost time.",
    
    // Happiness & Joy
    "Happiness is not something ready made. It comes from your own actions.",
    "The purpose of our lives is to be happy.",
    "Count your age by friends, not years. Count your life by smiles, not tears.",
    "Happiness is a choice, not a result.",
    "The happiest people don't have the best of everything, they just make the best of everything.",
    "Happiness depends upon ourselves.",
    "There is only one happiness in this life, to love and be loved.",
    "The secret of happiness is freedom, the secret of freedom is courage.",
    "Happiness is when what you think, what you say, and what you do are in harmony.",
    "Be happy for this moment. This moment is your life.",
    
    // Love & Relationships
    "The best thing to hold onto in life is each other.",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
    "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.",
    "Where there is love there is life.",
    "Love is composed of a single soul inhabiting two bodies.",
    "The best love is the kind that awakens the soul and makes us reach for more.",
    "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.",
    "To love and be loved is to feel the sun from both sides.",
    "Love is not about how much you say 'I love you,' but how much you can prove that it's true.",
    "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
    
    // Wisdom & Philosophy
    "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "The meaning of life is to find your gift. The purpose of life is to give it away.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "The best revenge is massive success.",
    "Life is really simple, but we insist on making it complicated.",
    "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
    "The unexamined life is not worth living.",
    "Life can only be understood backwards; but it must be lived forwards.",
    
    // Research Dreams & Academic Aspirations
    "All your career dreams can come true if you have the courage to complete your thesis.",
    "A thesis doesn't become reality through magic; it takes research, analysis, and persistent writing.",
    "The biggest academic adventure you can take is to contribute original knowledge to your field.",
    "If you can research it, analyze it, and write it, you can achieve it.",
    "Academic dreams don't work unless you consistently work on them.",
    "Follow your research questions, they will lead you to meaningful discoveries.",
    "Don't be paralyzed by imposter syndrome. Be driven by your passion for knowledge.",
    "Research hypotheses are the seedlings of academic breakthroughs.",
    "You are never too advanced to learn new research methodologies.",
    "The future belongs to those who believe in the power of their research contributions.",
    
    // Thesis Writing Action & Initiative
    "The way to finish your thesis is to quit overthinking and begin writing.",
    "A year from now you'll wish you had written that difficult chapter today.",
    "You don't have to write perfectly to get started, but you have to start writing to achieve excellence.",
    "The journey of a completed thesis begins with writing the first sentence.",
    "What you write today can transform your entire academic future.",
    "A well-written thesis is better than perfectly planned procrastination.",
    "A research idea not coupled with writing will never become a completed thesis.",
    "The path to graduation is to take consistent, focused writing actions daily.",
    "Don't wait for perfect research conditions, make this moment productive for your thesis.",
    "Consistent writing action is the foundational key to thesis completion.",
    
    // Creativity & Innovation
    "Creativity is intelligence having fun.",
    "The creative adult is the child who survived.",
    "Imagination is more important than knowledge.",
    "Creativity takes courage.",
    "You can't use up creativity. The more you use, the more you have.",
    "The secret to creativity is knowing how to hide your sources.",
    "Creativity is contagious, pass it on.",
    "Logic will get you from A to B. Imagination will take you everywhere.",
    "Every artist was first an amateur.",
    "Creativity is seeing what others see and thinking what no one else ever thought.",
    
    // Excellence & Quality
    "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "Quality is not an act, it is a habit.",
    "Strive for excellence, not perfection.",
    "Excellence is doing ordinary things extraordinarily well.",
    "The quality of a person's life is in direct proportion to their commitment to excellence.",
    "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.",
    "Excellence is the gradual result of always striving to do better.",
    "The pursuit of excellence is gratifying and healthy. The pursuit of perfection is frustrating, neurotic, and a terrible waste of time.",
    "Excellence is an art won by training and habituation.",
    
    // Faith & Spirituality
    "Faith is taking the first step even when you don't see the whole staircase.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Faith is the bird that feels the light when the dawn is still dark.",
    "With faith, discipline and selfless devotion to duty, there is nothing worthwhile that you cannot achieve.",
    "Faith is not something to grasp, it is a state to grow into.",
    "Faith includes noticing the mess, the emptiness and discomfort, and letting it be there until some light returns.",
    "Faith is the strength by which a shattered world shall emerge into the light.",
    "Faith is permitting ourselves to be seized by the things we do not see.",
    "Faith is the art of holding on to things your reason has once accepted, in spite of your changing moods.",
    
    // Adventure & Discovery
    "Life is either a daring adventure or nothing at all.",
    "Adventure is worthwhile in itself.",
    "The biggest adventure you can ever take is to live the life of your dreams.",
    "Man cannot discover new oceans unless he has the courage to lose sight of the shore.",
    "Adventure is not outside man; it is within.",
    "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.",
    "To travel is to live.",
    "Jobs fill your pocket, adventures fill your soul.",
    "Life begins at the end of your comfort zone.",
    "Adventure awaits, but only if you're brave enough to go find it.",
    
    // Health & Wellness
    "Take care of your body. It's the only place you have to live.",
    "Health is a state of complete harmony of the body, mind and spirit.",
    "The groundwork for all happiness is good health.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "A healthy outside starts from the inside.",
    "Health is not valued till sickness comes.",
    "The first wealth is health.",
    "Exercise is king. Nutrition is queen. Put them together and you've got a kingdom.",
    "Those who think they have no time for bodily exercise will sooner or later have to find time for illness.",
    "To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.",
    
    // Communication & Connection
    "The single biggest problem in communication is the illusion that it has taken place.",
    "To effectively communicate, we must realize that we are all different in the way we perceive the world and use this understanding as a guide to our communication with others.",
    "The art of communication is the language of leadership.",
    "Communication is a skill that you can learn. It's like riding a bicycle or typing. If you're willing to work at it, you can rapidly improve the quality of every part of your life.",
    "The most important thing in communication is hearing what isn't said.",
    "Good communication is as stimulating as black coffee, and just as hard to sleep after.",
    "Communication works for those who work at it.",
    "The way we communicate with others and with ourselves ultimately determines the quality of our lives.",
    "Words have energy and power with the ability to help, to heal, to hinder, to hurt, to harm, to humiliate and to humble.",
    "Listen with the intent to understand, not the intent to reply.",
    
    // Gratitude & Appreciation
    "Gratitude turns what we have into enough.",
    "Be thankful for what you have; you'll end up having more.",
    "Gratitude is not only the greatest of virtues, but the parent of all others.",
    "The unthankful heart discovers no mercies; but the thankful heart will find, in every hour, some heavenly blessings.",
    "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.",
    "Reflect upon your present blessings, of which every man has many - not on your past misfortunes, of which all men have some.",
    "As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them.",
    "Gratitude is a powerful catalyst for happiness. It's the spark that lights a fire of joy in your soul.",
    "The hardest thing in life is to know which bridge to cross and which to burn.",
    "Gratitude is the healthiest of all human emotions.",
    
    // Peace & Mindfulness
    "Peace comes from within. Do not seek it without.",
    "If you want to make peace with your enemy, you have to work with your enemy. Then he becomes your partner.",
    "Nobody can hurt me without my permission.",
    "You have power over your mind - not outside events. Realize this, and you will find strength.",
    "The present moment is the only time over which we have dominion.",
    "Wherever you are, be there totally.",
    "Peace is not absence of conflict, it is the ability to handle conflict by peaceful means.",
    "Do not let the behavior of others destroy your inner peace.",
    "When the power of love overcomes the love of power, the world will know peace.",
    "Peace cannot be kept by force; it can only be achieved by understanding.",
    
    // Hope & Optimism
    "Hope is being able to see that there is light despite all of the darkness.",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
    "Even the darkest night will end and the sun will rise.",
    "Hope is the thing with feathers that perches in the soul and sings the tune without the words and never stops at all.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "Hope is a waking dream.",
    "Once you choose hope, anything's possible.",
    "Hope is important because it can make the present moment less difficult to bear.",
    "We must accept finite disappointment, but never lose infinite hope.",
    "Hope smiles from the threshold of the year to come, whispering, 'It will be happier.'",
    
    // Learning & Growth
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.",
    "Learning never exhausts the mind.",
    "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
    "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.",
    "Learning is a treasure that will follow its owner everywhere.",
    "Education is the most powerful weapon which you can use to change the world.",
    "The beautiful thing about learning is that no one can take it away from you.",
    "I am always doing that which I cannot do, in order that I may learn how to do it.",
    "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.",
    
    // Kindness & Compassion
    "No act of kindness, no matter how small, is ever wasted.",
    "Kindness is a language which the deaf can hear and the blind can see.",
    "Be kind whenever possible. It is always possible.",
    "Carry out a random act of kindness, with no expectation of reward, safe in the knowledge that one day someone might do the same for you.",
    "Kindness is the sunshine in which virtue grows.",
    "A single act of kindness throws out roots in all directions, and the roots spring up and make new trees.",
    "Compassion is not religious business, it is human business, it is not luxury, it is essential for our own peace and mental stability.",
    "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.",
    "The best way to take care of the future is to take care of the present moment.",
    "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.",
    
    // Additional Powerful Quotes
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "What we plant in the soil of contemplation, we shall reap in the harvest of action.",
    "The mind is everything. What you think you become.",
    "Life shrinks or expands in proportion to one's courage.",
    "You are what you choose to be. You choose. Choose.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Don't let yesterday take up too much of today.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The most wasted of days is one without laughter.",
    "Turn your wounds into wisdom.",
    "If opportunity doesn't knock, build a door.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "A champion is someone who gets up when they can't.",
    "Fall seven times, stand up eight.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Be yourself, everyone else is taken.",
    "In the middle of difficulty lies opportunity.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "The future depends on what you do today.",
    "Everything you need is inside you – you just need to access it.",
    "Stars can't shine without darkness.",
    "Difficult roads often lead to beautiful destinations.",
    "Your only limit is your mind.",
    "Do what you can with all you have, wherever you are.",
    "If you're going through hell, keep going.",
    "Believe in yourself when nobody else does.",
    "Good things happen to those who work hard.",
    "Don't stop until you're proud.",
    "Make each day your masterpiece.",
    "Life begins where your comfort zone ends.",
    "Progress, not perfection.",
    "You are stronger than you think.",
    "Create your own sunshine.",
    "Be the energy you want to attract.",
    "Every expert was once a beginner.",
    "Small steps in the right direction can turn out to be the biggest step of your life.",
    "You are capable of amazing things.",
    "Don't wish it were easier; wish you were better.",
    "The comeback is always stronger than the setback.",
    "Your potential is endless.",
    "Embrace the glorious mess that you are.",
    "You were born to be real, not perfect.",
    "Today is the perfect day to start living your dreams.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Comparison is the thief of joy.",
    "You don't need to see the whole staircase, just take the first step.",
    "The world needs what you have to give.",
    "Your life is your message to the world. Make sure it's inspiring.",
    "Don't wait for inspiration. Be the inspiration.",
    "You are not here merely to make a living. You are here to enable the world to live more amply.",
    "The best project you'll ever work on is you.",
    "Be patient with yourself. Self-growth is tender; it's holy ground.",
    "You are enough just as you are.",
    "Trust the process. Your time is coming.",
    "Everything you've ever wanted is on the other side of fear.",
    "You didn't come this far to only come this far.",
    "Your story isn't over yet.",
    "Be proud of how far you've come. Have faith in how far you can go.",
    "You are the author of your own story. Write a good one.",
    "Don't let the fear of striking out keep you from playing the game.",
    "The difference between ordinary and extraordinary is that little 'extra'.",
    "You can't use up creativity. The more you use, the more you have.",
    "Your dreams are valid.",
    "Progress is impossible without change.",
    "The only way to predict the future is to create it.",
    "You are never too old to reinvent yourself.",
    "Every moment is a fresh beginning.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "The best revenge is massive success.",
    "Life is tough, but so are you.",
    "You have been assigned this mountain to show others it can be moved.",
    "Don't let what you cannot do interfere with what you can do.",
    "The expert in anything was once a beginner.",
    "Your current situation is not your final destination.",
    "Difficult doesn't mean impossible.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "The only way out is through.",
    "You've survived 100% of your worst days. You're doing great.",
    "Your speed doesn't matter, forward is forward.",
    "Rock bottom became the solid foundation on which I rebuilt my life.",
    "You are not stuck. You are not stuck. You are not stuck.",
    "This too shall pass.",
    "You are exactly where you need to be.",
    "Trust your journey.",
    "Everything is figureoutable.",
    "You got this.",
    "One day at a time.",
    "Keep going. You're getting there.",
    "Your comeback story starts now.",
    "Breathe in courage, breathe out fear.",
    "You are more resilient than you realize.",
    "Every storm runs out of rain.",
    "You are not your mistakes.",
    "Today's accomplishments were yesterday's impossibilities.",
    "You are writing your story one day at a time.",
    "The sun will rise and we will try again.",
    "You are exactly who you're supposed to be.",
    "Your journey is beautiful.",
    "You matter more than you know.",
    "Keep shining. The world needs your light.",
    "You are a work of art. Not everyone will understand you, but the ones who do, will never forget about you.",
    "Your story could be the key that unlocks someone else's prison.",
    "Be the reason someone believes in the goodness of people.",
    "You are not meant to shrink. You are meant to shine.",
    "Your wings already exist. All you have to do is fly.",
    "You are the hero of your own story.",
    "Don't dim your light for anyone.",
    "You are magic wrapped in human form.",
    "Your presence is a present to the world.",
    "You are loved more than you will ever know.",
    "You are a miracle.",
    "The world is better with you in it.",
    "You are enough. You have always been enough. You will always be enough.",
    "Your life has infinite value.",
    "You are irreplaceable.",
    "You are worthy of all the love in the world.",
    "You deserve all the happiness life has to offer.",
    "You are perfect exactly as you are.",
    "Your heart is pure magic.",
    "You are a blessing to everyone you meet.",
    "You are the light in someone's darkness.",
    "Your smile can change the world.",
    "You are someone's reason to smile.",
    "You make the world a better place just by being in it.",
    "You are a masterpiece in progress.",
    "Your potential is limitless.",
    "You are destined for greatness.",
    "The universe conspires to help you succeed.",
    "You attract what you are, not what you want.",
    "You are magnetic.",
    "You are a force of nature.",
    "You are unstoppable.",
    "You are invincible.",
    "You are phenomenal.",
    "You are extraordinary.",
    "You are magnificent.",
    "You are brilliant.",
    "You are amazing.",
    "You are incredible.",
    "You are wonderful.",
    "You are beautiful inside and out.",
    "You are a gift to this world.",
    "You are pure light.",
    "You are love incarnate.",
    "You are divine.",
    "You are infinite.",
    "You are eternal.",
    "You are everything.",
    
    // Additional Career & Thesis Specific Motivation
    "Your thesis is not just an assignment, it's your contribution to human knowledge.",
    "Every successful career started with someone who refused to give up on their education.",
    "Research is formalized curiosity. It is poking and prying with a purpose.",
    "The expert in anything was once a beginner who never gave up learning.",
    "Your degree is not just a piece of paper, it's proof of your persistence and intelligence.",
    "Academic challenges are not roadblocks, they're stepping stones to expertise.",
    "Thesis writing is like building a bridge between what you know and what the world needs to know.",
    "Every page you write brings you closer to the career you've always wanted.",
    "Your research today shapes the professional you become tomorrow.",
    "Graduation day will feel so much sweeter because of the late nights you're putting in now.",
    "Writer's block is temporary, but the regret of not finishing lasts forever.",
    "Your thesis committee believes in you, now it's time to believe in yourself.",
    "Academic success isn't about being the smartest person in the room, it's about being the most persistent.",
    "Every citation you write connects your work to the larger academic conversation.",
    "Your literature review isn't just summarizing others' work, it's building the foundation for your contribution.",
    "The methodology section isn't boring, it's the roadmap others will follow to build on your discoveries.",
    "Data analysis isn't just number crunching, it's uncovering the stories hidden in your research.",
    "Your conclusion isn't just the end of your thesis, it's the beginning of your professional impact.",
    "Peer review isn't criticism, it's the academic community helping you strengthen your contribution.",
    "Your defense isn't an interrogation, it's a celebration of your expertise.",
    "Academic writing isn't just about what you say, it's about how clearly you can say it.",
    "Research ethics aren't constraints, they're the foundation of trustworthy knowledge.",
    "Your thesis timeline isn't a prison, it's a scaffold supporting your success.",
    "Academic conferences aren't intimidating, they're opportunities to share your passion.",
    "Publishing isn't the end goal, it's the beginning of your scholarly conversation.",
    "Your advisor isn't your boss, they're your guide on the path to becoming an independent researcher.",
    "Revisions aren't setbacks, they're the polish that makes your work shine.",
    "Academic rejection isn't personal failure, it's redirection toward a better fit.",
    "Your thesis doesn't have to be perfect, it just has to be finished.",
    "The job market isn't a lottery, it's a meritocracy that rewards persistent excellence.",
    "Networking isn't schmoozing, it's building professional relationships that enrich your career.",
    "Your CV isn't a list of accomplishments, it's the story of your professional growth.",
    "Job interviews aren't tests, they're conversations about mutual fit and future collaboration.",
    "Career setbacks aren't endings, they're plot twists in your professional story.",
    "Professional development isn't optional, it's the fuel that powers career advancement.",
    "Your expertise isn't static, it grows with every project you complete.",
    "Industry trends aren't threats, they're opportunities for those prepared to adapt.",
    "Your professional network isn't transactional, it's a community of mutual support and growth.",
    "Career pivots aren't admissions of failure, they're strategic moves toward better alignment.",
    "Your unique perspective isn't a disadvantage, it's your competitive edge in the marketplace.",
    "Professional challenges aren't obstacles, they're training grounds for leadership skills."
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = motivationalQuotes;
}